/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.rand.kafkaproducer;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ImageBlock extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord, org.apache.avro.generic.GenericRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ImageBlock\",\"namespace\":\"kafkaproducer\",\"fields\":[{\"name\":\"filename\",\"type\":\"string\"},{\"name\":\"local_hash\",\"type\":\"string\"},{\"name\":\"data\",\"type\":\"bytes\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence filename;
  @Deprecated public java.lang.CharSequence local_hash;
  @Deprecated public java.nio.ByteBuffer data;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ImageBlock() {}

  /**
   * All-args constructor.
   */
  public ImageBlock(java.lang.CharSequence filename, java.lang.CharSequence local_hash, java.nio.ByteBuffer data) {
    this.filename = filename;
    this.local_hash = local_hash;
    this.data = data;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return filename;
    case 1: return local_hash;
    case 2: return data;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: filename = (java.lang.CharSequence)value$; break;
    case 1: local_hash = (java.lang.CharSequence)value$; break;
    case 2: data = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'filename' field.
   */
  public java.lang.CharSequence getFilename() {
    return filename;
  }

  /**
   * Sets the value of the 'filename' field.
   * @param value the value to set.
   */
  public void setFilename(java.lang.CharSequence value) {
    this.filename = value;
  }

  /**
   * Gets the value of the 'local_hash' field.
   */
  public java.lang.CharSequence getLocalHash() {
    return local_hash;
  }

  /**
   * Sets the value of the 'local_hash' field.
   * @param value the value to set.
   */
  public void setLocalHash(java.lang.CharSequence value) {
    this.local_hash = value;
  }

  /**
   * Gets the value of the 'data' field.
   */
  public java.nio.ByteBuffer getData() {
    return data;
  }

  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(java.nio.ByteBuffer value) {
    this.data = value;
  }

  /** Creates a new ImageBlock RecordBuilder */
  public static org.rand.kafkaproducer.ImageBlock.Builder newBuilder() {
    return new org.rand.kafkaproducer.ImageBlock.Builder();
  }
  
  /** Creates a new ImageBlock RecordBuilder by copying an existing Builder */
  public static org.rand.kafkaproducer.ImageBlock.Builder newBuilder(org.rand.kafkaproducer.ImageBlock.Builder other) {
    return new org.rand.kafkaproducer.ImageBlock.Builder(other);
  }
  
  /** Creates a new ImageBlock RecordBuilder by copying an existing ImageBlock instance */
  public static org.rand.kafkaproducer.ImageBlock.Builder newBuilder(org.rand.kafkaproducer.ImageBlock other) {
    return new org.rand.kafkaproducer.ImageBlock.Builder(other);
  }
  
  /**
   * RecordBuilder for ImageBlock instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ImageBlock>
    implements org.apache.avro.data.RecordBuilder<ImageBlock> {

    private java.lang.CharSequence filename;
    private java.lang.CharSequence local_hash;
    private java.nio.ByteBuffer data;

    /** Creates a new Builder */
    private Builder() {
      super(org.rand.kafkaproducer.ImageBlock.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.rand.kafkaproducer.ImageBlock.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.filename)) {
        this.filename = data().deepCopy(fields()[0].schema(), other.filename);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.local_hash)) {
        this.local_hash = data().deepCopy(fields()[1].schema(), other.local_hash);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.data)) {
        this.data = data().deepCopy(fields()[2].schema(), other.data);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ImageBlock instance */
    private Builder(org.rand.kafkaproducer.ImageBlock other) {
            super(org.rand.kafkaproducer.ImageBlock.SCHEMA$);
      if (isValidValue(fields()[0], other.filename)) {
        this.filename = data().deepCopy(fields()[0].schema(), other.filename);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.local_hash)) {
        this.local_hash = data().deepCopy(fields()[1].schema(), other.local_hash);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.data)) {
        this.data = data().deepCopy(fields()[2].schema(), other.data);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'filename' field */
    public java.lang.CharSequence getFilename() {
      return filename;
    }
    
    /** Sets the value of the 'filename' field */
    public org.rand.kafkaproducer.ImageBlock.Builder setFilename(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.filename = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'filename' field has been set */
    public boolean hasFilename() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'filename' field */
    public org.rand.kafkaproducer.ImageBlock.Builder clearFilename() {
      filename = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'local_hash' field */
    public java.lang.CharSequence getLocalHash() {
      return local_hash;
    }
    
    /** Sets the value of the 'local_hash' field */
    public org.rand.kafkaproducer.ImageBlock.Builder setLocalHash(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.local_hash = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'local_hash' field has been set */
    public boolean hasLocalHash() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'local_hash' field */
    public org.rand.kafkaproducer.ImageBlock.Builder clearLocalHash() {
      local_hash = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'data' field */
    public java.nio.ByteBuffer getData() {
      return data;
    }
    
    /** Sets the value of the 'data' field */
    public org.rand.kafkaproducer.ImageBlock.Builder setData(java.nio.ByteBuffer value) {
      validate(fields()[2], value);
      this.data = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'data' field has been set */
    public boolean hasData() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'data' field */
    public org.rand.kafkaproducer.ImageBlock.Builder clearData() {
      data = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public ImageBlock build() {
      try {
        ImageBlock record = new ImageBlock();
        record.filename = fieldSetFlags()[0] ? this.filename : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.local_hash = fieldSetFlags()[1] ? this.local_hash : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.data = fieldSetFlags()[2] ? this.data : (java.nio.ByteBuffer) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
